[package]
name = "roget"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = true

[dependencies]
core_simd = { git = "https://github.com/rust-lang/portable-simd" }
clap = { version = "3", features = ["derive"] }
once_cell = "1"
